### ISSUE TITLE
Imprecise and low quality drawing

### ISSUE THREAD

**Issue by GreenComfyTea** [cursey/reframework-d2d#2]
**Problem:**
The precision of positioning when using `d2d.*` is lower than when using `draw.*`. On videos below the health bar is drawn using `draw.world_to_screen(monster.position)`. Using those coordinates in `d2d.fill_rect` gives pretty shaky results while `draw.filled_rect` is drawn smoothly.
The quality of text is also seems lower.

(Also maybe rename fill_rect to filled_rect to match one from imgui?)

**Videos:**
**Using d2d:** https://mega.nz/file/PXpmlYKZ#df7uouat9Y28nzCKqlW6FnvpFJ-Rq_kzUH39URPZLNM
**Using imgui:** https://mega.nz/file/6S42AK7L#0De71chimYuJ1y7VWPJE60x0f8EhKF0zrGGaiYMQBrE

**Comment by cursey** [comment]
> The precision of positioning when using `d2d.*` is lower than when using `draw.*`. On videos below the health bar is drawn using `draw.world_to_screen(monster.position)`. Using those coordinates in `d2d.fill_rect` gives pretty shaky results while `draw.filled_rect` is drawn smoothly.

This is entirely because `d2d` updates at a lower rate than the `draw` API (currently hardcoded to update at 30hz). The rationale for this is simple. Many overlays do quite a bit of work in their draw functions and can cause a non-negligible performance impact for users if ran every single frame. 

I plan on making the rate at which `d2d` updates user configurable, I just didn't get to it in time for first release.

> The quality of text is also seems lower.

You're using a different font so I can't tell what you mean. Can you show a clear example of how the quality is lower? 

If you want to do a direct comparison, install Roboto Medium on your computer and use that for REFramework-D2D to really compare the results.

**Comment by cursey** [comment]
> The precision of positioning when using `d2d.*` is lower than when using `draw.*`. On videos below the health bar is drawn using `draw.world_to_screen(monster.position)`. Using those coordinates in `d2d.fill_rect` gives pretty shaky results while `draw.filled_rect` is drawn smoothly.

Fixed in 2da844794860b5fd46b60b83f409291a1f623672. Make sure to copy the new `/scripts/autorun/reframework-d2d.lua` over so you can configure the max update rate yourself. The default has been increased to 60hz though (instead of 30hz).

> (Also maybe rename fill_rect to filled_rect to match one from imgui?)

Fixed in 9a55217287b937d9987d964232b5789d05d14ef7

I've also improved error handling and fixed the freezing issue in abfdda273fc0b1fe05a4093feec931324fd14721. 

Let me know if this addresses all the reported issues for you.

**Comment by cursey** [comment]
> The quality of text is also seems lower.

I think I've probably fixed this in 0edfaf97e0c58104f8a7b9d33639f1fd783ccb9b.

**Comment by GreenComfyTea** [comment]
I see. As always thank you for your hard work. I automatically assumed it is at least 60Hz so didn't of from that perspective. Allowing user to configure it is a good choice.
Improvement: maybe add auto refresh rate option: when enabled refresh rate matches the refresh rate of the screen?

Font quality (on the old version):
`roboto_font = d2d.create_font("Roboto", 13, true)`:
 (should i be passing `"Roboto Medium"` or `"Roboto-Medium"` or `"RobotoMedium"`?)
![image](https://user-images.githubusercontent.com/30152047/151695351-69934c71-3ae3-4e39-bd68-76fed236fcbb.png)
`roboto_font = d2d.create_font("Roboto", 13, false)`:
![image](https://user-images.githubusercontent.com/30152047/151695411-9f9eea6c-c461-4a66-a8d1-09ceaa4ab335.png)

Idk something feels off. For example the top of **`t`** is slightly blurred on d2d bold font.

**Comment by cursey** [comment]
> Font quality (on the old version): `roboto_font = d2d.create_font("Roboto", 13, true)`: (should i be passing `"Roboto Medium"` or `"Roboto-Medium"` or `"RobotoMedium"`?) ![image](https://user-images.githubusercontent.com/30152047/151695351-69934c71-3ae3-4e39-bd68-76fed236fcbb.png) `roboto_font = d2d.create_font("Roboto", 13, false)`: ![image](https://user-images.githubusercontent.com/30152047/151695411-9f9eea6c-c461-4a66-a8d1-09ceaa4ab335.png)
> 
> Idk something feels off. For example the top of **`t`** is slightly blurred on d2d bold font.

I think its user preference at that point. I personally prefer the plugins output in your example (both bold and regular). I'm a big fan of DirectWrite output though so I may be biased.

**Comment by GreenComfyTea** [comment]
I am fan of DirectWrite too. But doesn't imgui uses DirectWrite too? I would have expected same results.

> I think its user preference at that point. 

You are about this thou xD

**Comment by cursey** [comment]
> But doesn't imgui uses DirectWrite too? I would have expected same results.

imgui uses [stb_truetype](https://github.com/nothings/stb/blob/master/stb_truetype.h) which is a very simple font rasterizer.

**Comment by GreenComfyTea** [comment]
Fair enough. I have no more complaints xD

**Comment by cursey** [comment]
> Improvement suggestion: maybe add auto refresh rate option: when enabled refresh rate matches the refresh rate of the screen (or the game)?

This can be accomplished by just setting the max update rate to 300 (or any rate higher than their normal framerate). Assuming people don't hit 300 FPS, it will just run as fast as their FPS.
